uipath: add new version for custom template
camunda/connectors-bundle pull request #212
Opened 2023-01-16 12:24 UTC by mbiciin

## Related issues

#210

2023-01-16 14:02 UTC, bastiankoerber requested changes
i changed a lot.

2023-01-18 07:22 UTC, mbiciin commented
The template is not finished. The last part concerning the input fields "Item id" and "Item status" is work in progress. As disscussed, we should let the user type the name of the variable in the input field "Item Id" and bind it with the value return by the resultExpression {itemId: response.body.id}. We don't know if it's possible yet. I'll have a meeting with a collegue from web-modeler team today.

2023-01-19 08:41 UTC, bastiankoerber commented
@mbiciin is this the final version?

2023-01-19 08:44 UTC, bastiankoerber commented on connectors/uipath/element-templates/uipath-custom-template.json
> +  "documentationRef": "https://docs.camunda.io/docs/components/modeler/web-modeler/connectors/available-connectors/rest/",
link to the new documentation

2023-01-19 08:44 UTC, bastiankoerber commented on connectors/uipath/element-templates/uipath-custom-template.json
> +    "contents": "data:image/svg+xml;utf8,%3C%3Fxml version='1.0' encoding='utf-8'%3F%3E%3Csvg version='1.1' id='Extra_Large' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xli
add UIPath logo

2023-01-19 11:08 UTC, bastiankoerber commented on connectors/uipath/element-templates/uipath-custom-template.json
> +      "label": "Specific Content for UIPath Job",
for me it was just working with an feel expression. if it is like this, then set feel as required

2023-01-19 12:03 UTC, bastiankoerber requested changes
please change url to documentation, add expected dateformat and check specific content with feel expression

2023-01-19 12:42 UTC, bastiankoerber approved these changes
awesome, looks good to me :-)

2023-01-20 11:21 UTC, nikku commented
@bastiankoerber I investigated together with @mbiciin one requirement that you had:

> As a user I want to map a specific part of the execution result back to the process (for tracking, further processing)

This is absolutely possible using on board facilities:

* Define an input variable mapping for `resultVariableName`

* Use that variable to dynamically construct a response mapping context
  
  ```
  if 
    resultVariableName = null
  then 
    {}
  else
    put({ }, resultVariableName, response.body.Id)
  ```

Two general comments of what @mbiciin mentioned: 

* We may defined default output mappings, but we should never do that magically (i.e. if `resultVariableName` is not provided, _always_ write a `itemID` variable). This is dangerous and violates the no surprises property: https://github.com/bpmn-io/design-principles#no-surprises

At this stage you cannot map dynamically constructed outputs _and_ offer the default mapping:

![image](https://user-images.githubusercontent.com/58601/213683277-7870850f-1171-464a-8dae-01c54df9e04b.png)

My suggestion is to keep the default output mapping facility in place as it allows users to not only extract default data, but also access additional diagnostics data that we don't want to offer via explicit template propertiesin the UI (`Item ID NAME`). 

In the future we'll offer dedicated editor tooling for dynamic mapping making that even simpler: 
![image](https://user-images.githubusercontent.com/58601/213683569-9c71e7a3-046f-4ecf-901a-47569822db1d.png)

2023-01-20 13:35 UTC, mbiciin commented
@nikku, I forgot to tell you in our meeting that we need to use this itemId in "Filters", which is a parameter for query 'getItemStatus'. The expression still evaluetes to {"$Filter":null} which is not correct. For example, I should have {"$Filter":"Id eq 436141352"}. 

<img width="1545" alt="Screen Shot 2023-01-20 at 3 22 35 PM" src="https://user-images.githubusercontent.com/114916619/213705048-1e9a3b1a-bb20-44b5-a177-cab8dd04fe94.png">

Here is the filter:
```
{
      "label": "Filters",
      "description": "Map of query parameters to add to the request URL",
      "group": "input",
      "type": "Hidden",
      "value": "={\"$Filter\":\"Id eq \"+string(itemId)}",
      "binding": {
        "type": "zeebe:input",
        "name": "queryParameters"
      },
      "condition": {
        "property": "operationType",
        "oneOf": [
          "getItemStatus"
        ]
      }
    }
```

More info about it here: https://github.com/camunda/connectors-bundle/issues/210#issuecomment-1387421948

2023-01-26 13:32 UTC, merged